-- Run this in Supabase SQL Editor before switching the app to cloud persistence.
create table if not exists stores (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  store_id bigint not null references stores(id) on delete cascade,
  name text not null,
  available_days text not null default '',
  available_shifts text not null default '',
  preferred_days_off text not null default '',
  email text,
  line_user_id text,
  updated_at timestamptz not null default now(),
  unique(store_id, name)
);

create table if not exists schedule_versions (
  id bigint generated by default as identity primary key,
  store_id bigint not null references stores(id) on delete cascade,
  week_start date not null,
  schedule_json jsonb not null,
  gaps_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists leave_requests (
  id bigint generated by default as identity primary key,
  store_id bigint not null references stores(id) on delete cascade,
  requester text not null,
  employee_name text not null,
  start_date date not null,
  end_date date not null,
  reason text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by text,
  created_at timestamptz not null default now()
);

create table if not exists swap_requests (
  id bigint generated by default as identity primary key,
  store_id bigint not null references stores(id) on delete cascade,
  requester text not null,
  from_employee text not null,
  to_employee text not null,
  shift_date date not null,
  shift_name text not null,
  reason text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by text,
  created_at timestamptz not null default now()
);

alter table employees enable row level security;
alter table stores enable row level security;
alter table schedule_versions enable row level security;
alter table leave_requests enable row level security;
alter table swap_requests enable row level security;
